export const pdfs = [
  { name: "Pension Summary", value: 29 },
  { name: "Marketing Teaser", value: 31 },
  { name: "Plan Design", value: 30 },
  { name: "ERISA Check List", value: 1 },
  { name: "ERISA 404c Check List", value: 2 },
  { name: "401k Checklist", value: 3 },
  { name: "Auditor Checklist", value: 6 },
  { name: "Auditor Report Checklist", value: 7 },
  { name: "Automatic Enrollment - CheckList", value: 15 },
  { name: "QDIA Checklist", value: 8 },
  { name: "Why Have a QDIA Offering?", value: 23 },
  { name: "Target Date Fund Guidelines", value: 10 },
  { name: "Selecting an Annuity Provider", value: 12 },
  { name: "Company Stock Overview", value: 13 },
  { name: "Automatic Enrollment - Benefits", value: 14 },
  { name: "Cash Balance Explained", value: 16 },
  { name: "Service Provider Disclosures", value: 19 },
  { name: "Plan Fee Descriptions", value: 20 },
  { name: "Evaluation of Plan Fees Guidelines", value: 21 },
  { name: "Leakage : Explained", value: 25 },
  { name: "Ideas to Increase Plan Participation", value: 26 },
  { name: "Types of Bonus Incentive Plans", value: 28 },
  { name: "Disclosure Guidelines", value: 4 },
  { name: "QDIA Investment types", value: 9 },
  { name: "TDF Basics", value: 24 },
  { name: "TDF Summary Guidelines", value: 27 },
];

export const marketingPdfs = [
  {
    name: "ERISA Check List",
    value: 1,
    hint: "Sponsor Compliance Requirements",
  },
  {
    name: "ERISA 404c Check List",
    value: 2,
    hint: "Sponsor Compliance Requirements",
  },
  { name: "401k Checklist", value: 3, hint: "Sponsor Compliance Requirements" },
  { name: "Auditor Checklist", value: 6, hint: "Selecting Auditor Check List" },
  {
    name: "Auditor Report Checklist",
    value: 7,
    hint: "Audit Report Questions",
  },
  {
    name: "Automatic Enrollment - CheckList",
    value: 15,
    hint: "Requirements ",
  },
  { name: "QDIA Checklist", value: 8, hint: "Compliance Requirements" },
  { name: "Why Have a QDIA Offering?", value: 23, hint: "-" },
  { name: "Target Date Fund Guidelines", value: 10, hint: "Review of TDF" },
  { name: "Selecting an Annuity Provider", value: 12, hint: "Guidelines" },
  {
    name: "Company Stock Overview",
    value: 13,
    hint: "Sponsor Compliance Requirements",
  },
  {
    name: "Evaluation of Plan Fees Guidelines",
    value: 21,
    hint: "Sponsor Compliance Requirements",
  },
  {
    name: "Automatic Enrollment - Benefits",
    value: 14,
    hint: "Why have Automatic Enrollment",
  },
  {
    name: "Cash Balance Explained",
    value: 16,
    hint: "Highlights & Definitions",
  },
  {
    name: "Service Provider Disclosures",
    value: 19,
    hint: "Compliance Requirements",
  },
  {
    name: "Plan Fee Descriptions",
    value: 20,
    hint: "Explanations & Definitions",
  },
  {
    name: "Leakage : Explained",
    value: 25,
    hint: "Explanations & Definitions",
  },
  {
    name: "Ideas to Increase Plan Participation",
    value: 26,
    hint: "Advisor Ideas & Suggestion",
  },
  {
    name: "Types of Bonus Incentive Plans",
    value: 28,
    hint: "Talent Retention",
  },
  { name: "Disclosure Guidelines", value: 4, hint: "Compliance Requirements" },
  {
    name: "QDIA Investment types",
    value: 9,
    hint: "Explanations & Definitions",
  },
  { name: "TDF Basics", value: 24, hint: "Summary Description" },
  { name: "TDF Summary Guidelines", value: 27, hint: "TDF Selection" },
  {
    name: "WA Advisor Advantage",
    value: 33,
    hint: "Coming soon",
    future: true,
  },
];
