export const codes = [
  {
    id: "1",
    Service3: "Administration",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1111",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Account Maintenance",
  },
  {
    id: "1112",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Claims Processing",
  },
  {
    id: "1113",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Communications - Participants",
  },
  {
    id: "1114",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Copying and Duplicating",
  },
  {
    id: "1115",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Fees - Shareholder Servicing",
  },
  {
    id: "1116",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Loan Processing - Participants",
  },
  {
    id: "1117",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Recordkeeping",
  },
  {
    id: "1118",
    Service3Code: "1",
    Service3: "Administration",
    Service2: "Recordkeeping and Management Reports",
  },
  {
    id: "4",
    Service3: "Brokerage",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "41",
    Service3Code: "4",
    Service3: "Brokerage",
    Service2: "Brokerage - Insurance/Fees",
  },
  {
    id: "42",
    Service3Code: "4",
    Service3: "Brokerage",
    Service2: "Brokerage - Real Estate",
  },
  {
    id: "43",
    Service3Code: "4",
    Service3: "Brokerage",
    Service2: "Brokerage - Securities",
  },
  {
    id: "44",
    Service3Code: "4",
    Service3: "Brokerage",
    Service2: "Brokerage - Securities Commissions/Fees",
  },
  {
    id: "7",
    Service3: "Custody",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "7111",
    Service3Code: "7",
    Service3: "Custody",
    Service2: "Custodial Services",
  },
  {
    id: "7112",
    Service3Code: "7",
    Service3: "Custody",
    Service2: "Custodial Services - Other",
  },
  {
    id: "10",
    Service3: "Governance",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1011",
    Service3Code: "10",
    Service3: "Governance",
    Service2: "Contract Administrator",
  },
  {
    id: "1012",
    Service3Code: "10",
    Service3: "Governance",
    Service2: "Fiduciary",
  },
  {
    id: "1013",
    Service3Code: "10",
    Service3: "Governance",
    Service2: "Plan Administrator",
  },
  {
    id: "5",
    Service3: "Insurance",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "5111",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Fees  - Insurance wrap/Other",
  },
  {
    id: "5112",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Fees - Insurance Mortality Charge",
  },
  {
    id: "5113",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Fees - Other Insurance Expenses",
  },
  {
    id: "5114",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Fees - Product Terminination/Surrender",
  },
  {
    id: "5115",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Insurance - Agent/Broker",
  },
  {
    id: "5116",
    Service3Code: "5",
    Service3: "Insurance",
    Service2: "Insurance Services",
  },
  {
    id: "15",
    Service3: "International",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1511",
    Service3Code: "15",
    Service3: "International",
    Service2: "Foreign Entity",
  },
  {
    id: "2",
    Service3: "Investment Management",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "2111",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Fees - Other Investment Expenses",
  },
  {
    id: "2112",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Investment - Direct Payments by Plan",
  },
  {
    id: "2113",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Investment - Indirect Payments by Plan",
  },
  {
    id: "2114",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Investment - Participant Advisory",
  },
  {
    id: "2115",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Investment - Plan Advisory",
  },
  {
    id: "2116",
    Service3Code: "2",
    Service3: "Investment Management",
    Service2: "Investment Management",
  },
  {
    id: "12",
    Service3: "Other",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1211",
    Service3Code: "12",
    Service3: "Other",
    Service2: "Compensation - Non Monetary",
  },
  { id: "1212", Service3Code: "12", Service3: "Other", Service2: "Other" },
  {
    id: "1213",
    Service3Code: "12",
    Service3: "Other",
    Service2: "Other - Commissions",
  },
  {
    id: "1214",
    Service3Code: "12",
    Service3: "Other",
    Service2: "Other - Services",
  },
  {
    id: "14",
    Service3: "Other Charges",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1411",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Distribution/12B-1",
  },
  {
    id: "1412",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Finders/Placement",
  },
  {
    id: "1413",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Float Revenue",
  },
  {
    id: "1414",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Redemption fees",
  },
  {
    id: "1415",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Soft dollar Commissions",
  },
  {
    id: "1416",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Fees - Subtransfer Agency",
  },
  {
    id: "1417",
    Service3Code: "14",
    Service3: "Other Charges",
    Service2: "Sales loads",
  },
  {
    id: "17",
    Service3: "Plan - Employee",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1711",
    Service3Code: "17",
    Service3: "Plan - Employee",
    Service2: "Employee - Plan",
  },
  {
    id: "1712",
    Service3Code: "17",
    Service3: "Plan - Employee",
    Service2: "Plan Sponsor - Employee",
  },
  {
    id: "13",
    Service3: "Plan Directed",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1311",
    Service3Code: "13",
    Service3: "Plan Directed",
    Service2: "Plan - Direct Payment",
  },
  {
    id: "3",
    Service3: "Professional Fees",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "3111",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Accounting/Audit",
  },
  {
    id: "3112",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Actuarial",
  },
  {
    id: "3113",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Consulting",
  },
  {
    id: "3114",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "General Consulting",
  },
  {
    id: "3115",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Legal",
  },
  {
    id: "3116",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Pension Consulting",
  },
  {
    id: "3117",
    Service3Code: "3",
    Service3: "Professional Fees",
    Service2: "Valuation/Appraisal",
  },
  {
    id: "16",
    Service3: "Trust",
    parent: true,
    overall2017: 0,
    overall2018: 0,
    overall2019: 0,
    industry: 0,
  },
  {
    id: "1611",
    Service3Code: "16",
    Service3: "Trust",
    Service2: "Trustee - Directed",
  },
  {
    id: "1612",
    Service3Code: "16",
    Service3: "Trust",
    Service2: "Trustee - Discretionary",
  },
  {
    id: "1613",
    Service3Code: "16",
    Service3: "Trust",
    Service2: "Trustee - Individual",
  },
  {
    id: "1614",
    Service3Code: "16",
    Service3: "Trust",
    Service2: "Trustee - Institutional",
  },
];
