//******STATES */
const state = [
  { name: "Alaska", abbriviation: "AK" },
  { name: "Alabama", abbriviation: "AL" },
  { name: "Arkansas", abbriviation: "AR" },
  { name: "Arizona", abbriviation: "AZ" },
  { name: "California", abbriviation: "CA" },
  { name: "Colorado", abbriviation: "CO" },
  { name: "Connecticut", abbriviation: "CT" },
  { name: "Delaware", abbriviation: "DE" },
  { name: "Florida", abbriviation: "FL" },
  { name: "Georgia", abbriviation: "GA" },
  { name: "Hawaii", abbriviation: "HI" },
  { name: "Iowa", abbriviation: "IA" },
  { name: "Idaho", abbriviation: "ID" },
  { name: "Illinois", abbriviation: "IL" },
  { name: "Indiana", abbriviation: "IN" },
  { name: "Kansas", abbriviation: "KS" },
  { name: "Kentucky", abbriviation: "KY" },
  { name: "Louisiana", abbriviation: "LA" },
  { name: "Massachusetts", abbriviation: "MA" },
  { name: "Maryland", abbriviation: "MD" },
  { name: "Maine", abbriviation: "ME" },
  { name: "Michigan", abbriviation: "MI" },
  { name: "Minnesota", abbriviation: "MN" },
  { name: "Missouri", abbriviation: "MO" },
  { name: "Mississippi", abbriviation: "MS" },
  { name: "Montana", abbriviation: "MT" },
  { name: "North Carolina", abbriviation: "NC" },
  { name: "North Dakota", abbriviation: "ND" },
  { name: "Nebraska", abbriviation: "NE" },
  { name: "New Hampshire", abbriviation: "NH" },
  { name: "New Jersey", abbriviation: "NJ" },
  { name: "New Mexico", abbriviation: "NM" },
  { name: "Nevada", abbriviation: "NV" },
  { name: "New York", abbriviation: "NY" },
  { name: "Ohio", abbriviation: "OH" },
  { name: "Oklahoma", abbriviation: "OK" },
  { name: "Oregon", abbriviation: "OR" },
  { name: "Pennsylvania", abbriviation: "PA" },
  { name: "Rhode Island", abbriviation: "RI" },
  { name: "South Carolina", abbriviation: "SC" },
  { name: "South Dakota", abbriviation: "SD" },
  { name: "Tennessee", abbriviation: "TN" },
  { name: "Texas", abbriviation: "TX" },
  { name: "Utah", abbriviation: "UT" },
  { name: "Virginia", abbriviation: "VA" },
  { name: "Vermont", abbriviation: "VT" },
  { name: "Washington", abbriviation: "WA" },
  { name: "Washington D.C.", abbriviation: "DC" },
  { name: "Wisconsin", abbriviation: "WI" },
  { name: "West Virginia", abbriviation: "WV" },
  { name: "Wyoming", abbriviation: "WY" },
];

export default state;
